using System.Threading.Tasks;
using Accord.Common.Attributes;
using OculusStudios.Platform.Oculus;

namespace BeatSaberQuestPatch.Patches;

/// <summary>
/// The goal of this patch is to reduce amount of noise in logs.
/// Oculus tries to fetch the token each time it needs to do a call that needs to be used with a token
///
/// Things such as in-app purchases still work, it's mostly non-essential things like Leaderboards that do not work.
/// </summary>
[AccordPatch(
    declaringType: typeof(PlatformUser), 
    methodName: "InternalGetAccessTokenAsync", 
    arguments: [])]
[AccordPrefix]
public partial class StopTryingGettingToken
{
    /// <summary>
    /// Patch is a source generated function from [AccordPatch] attribute
    /// It calls the following code
    /// Accord.RuntimeManager.Instance.Patch(this);
    /// </summary>
    public StopTryingGettingToken()
    {
        Patch();
    }

    /// <summary>
    /// Prefix is called before the original method
    /// The signature is generated by C# Source Generator
    /// </summary>
    /// <param name="instance"></param>
    /// <param name="returnValue"></param>
    /// <returns>true or false depending on if you want original function to be called</returns>
    public bool Prefix(PlatformUser instance, ref Task returnValue)
    {
        returnValue = Task.CompletedTask;
        return false;
    }
}